# Generated by Django 4.2.2 on 2023-06-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, verbose_name='Ad')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-Posta')),
                ('title', models.CharField(blank=True, verbose_name='Başlık')),
                ('text', models.CharField(blank=True, verbose_name='Mesaj')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Tarih')),
            ],
        ),
    ]
