# Generated by Django 4.2.2 on 2023-06-13 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('Developer', 'Geliştirici'), ('User', 'Kullanıcı')], default='User'),
        ),
    ]
