# Generated by Django 4.2.2 on 2023-06-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_pp_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='pp',
            field=models.ImageField(blank=True, default='/static/images/logo.png', upload_to='media/images/accounts/profile_photos/%Y/%m/%d', verbose_name='Profil fotoğrafı'),
        ),
    ]
