# Generated by Django 4.2.2 on 2023-06-29 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_pp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='bio',
            new_name='biography',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='pp',
            new_name='profile_photo',
        ),
    ]
