# Generated by Django 4.2.2 on 2023-07-27 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_bio_customuser_biography_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='E-Posta onay durumu'),
        ),
    ]
