# Generated by Django 4.2.2 on 2023-07-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customuser_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(choices=[('Non-verified', 'Onaylanmamış'), ('Verified', 'Onaylanmış')], default='Non-verified'),
        ),
    ]
