# Generated by Django 4.2.2 on 2023-07-27 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_customuser_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_verified',
            field=models.CharField(choices=[('Nonverified', 'Onaylanmamış'), ('Verified', 'Onaylanmış')], default='Nonverified'),
        ),
    ]
