# Generated by Django 4.2.2 on 2023-08-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_customuser_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_photo',
            field=models.ImageField(blank=True, default='/static/images/logo.png', null=True, upload_to='images/accounts/profile_photos/%Y/%m/%d', verbose_name='Profil fotoğrafı'),
        ),
    ]
