# Generated by Django 4.2.2 on 2023-08-06 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_customuser_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_photo',
            field=models.ImageField(blank=True, default='images/accounts/profile_photos/logo.png', null=True, upload_to='images/accounts/profile_photos/%Y/%m/%d', verbose_name='Profil fotoğrafı'),
        ),
    ]
