# Generated by Django 4.2.2 on 2023-08-06 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_customuser_profile_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='biography',
            new_name='bio',
        ),
    ]
