# Generated by Django 4.2.2 on 2023-08-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_rename_is_verified_customuser_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_mail_sent',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
