# Generated by Django 4.2.2 on 2023-08-07 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_customuser_last_mail_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='last_mail_sent',
        ),
    ]
