# Generated by Django 4.2.2 on 2023-06-12 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(auto_now_add=True, verbose_name='Satın alım tarihi.')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Satın alım tutarı.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Satın alımı yapan kullanıcı.')),
            ],
        ),
        migrations.CreateModel(
            name='LicenseKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(verbose_name='Lisans anahtarı.')),
                ('end_date', models.DateField(verbose_name='Lisansın sona eriş tarihi.')),
                ('purchase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='program.purchase', verbose_name='Satılan lisans anahtarı.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Anahtarın sahibi.')),
            ],
        ),
    ]
