# Generated by Django 4.2.2 on 2023-06-14 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensekey',
            name='key',
            field=models.CharField(unique=True, verbose_name='Lisans anahtarı.'),
        ),
        migrations.AlterField(
            model_name='licensekey',
            name='purchase',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='program.purchase', verbose_name='Satılan lisans anahtarı.'),
        ),
    ]
