# Generated by Django 4.2.2 on 2023-06-14 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_alter_licensekey_key_alter_licensekey_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensekey',
            name='purchase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='program.purchase', verbose_name='Satılan lisans anahtarı.'),
        ),
    ]
