# Generated by Django 4.2.2 on 2023-06-14 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0003_alter_licensekey_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licensekey',
            name='user',
        ),
        migrations.AlterField(
            model_name='licensekey',
            name='end_date',
            field=models.DateField(verbose_name='Lisansın sona eriş tarihi:'),
        ),
        migrations.AlterField(
            model_name='licensekey',
            name='key',
            field=models.CharField(unique=True, verbose_name='Lisans anahtarı:'),
        ),
        migrations.AlterField(
            model_name='licensekey',
            name='purchase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='program.purchase', verbose_name='Satın alım:'),
        ),
    ]
