# Generated by Django 4.2.2 on 2023-06-14 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0004_remove_licensekey_user_alter_licensekey_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensekey',
            name='key_type',
            field=models.CharField(choices=[('BSC', 'Temel'), ('STD', 'Standart'), ('PRO', 'Profesyonel')], default='BSC', verbose_name='Lisans türü:'),
        ),
        migrations.AddField(
            model_name='licensekey',
            name='uuid1',
            field=models.UUIDField(null=True, verbose_name='UUID 1:'),
        ),
        migrations.AddField(
            model_name='licensekey',
            name='uuid2',
            field=models.UUIDField(null=True, verbose_name='UUID 2:'),
        ),
    ]
