# Generated by Django 4.2.2 on 2023-06-14 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0005_licensekey_key_type_licensekey_uuid1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensekey',
            name='uuid1',
            field=models.UUIDField(blank=True, null=True, verbose_name='UUID 1:'),
        ),
        migrations.AlterField(
            model_name='licensekey',
            name='uuid2',
            field=models.UUIDField(blank=True, null=True, verbose_name='UUID 2:'),
        ),
    ]
