# Generated by Django 4.2.2 on 2023-06-14 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0006_alter_licensekey_uuid1_alter_licensekey_uuid2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LicenseKey',
            new_name='LicenceKey',
        ),
    ]
