# Generated by Django 4.2.2 on 2023-06-14 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0007_rename_licensekey_licencekey'),
    ]

    operations = [
        migrations.RenameField(
            model_name='licencekey',
            old_name='key_type',
            new_name='type',
        ),
    ]
