# Generated by Django 4.2.2 on 2023-06-14 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0008_rename_key_type_licencekey_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licencekey',
            name='type',
        ),
        migrations.AddField(
            model_name='licencekey',
            name='key_type',
            field=models.CharField(choices=[('BSC', 'Temel'), ('STD', 'Standart'), ('PRO', 'Profesyonel')], default='BSC', verbose_name='Lisans tipi:'),
        ),
    ]
