# Generated by Django 4.2.2 on 2023-06-14 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0009_remove_licencekey_type_licencekey_key_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licencekey',
            name='uuid1',
        ),
        migrations.RemoveField(
            model_name='licencekey',
            name='uuid2',
        ),
        migrations.AddField(
            model_name='licencekey',
            name='disk_serial_number1',
            field=models.IntegerField(blank=True, null=True, verbose_name='UUID 1:'),
        ),
        migrations.AddField(
            model_name='licencekey',
            name='disk_serial_number2',
            field=models.IntegerField(blank=True, null=True, verbose_name='UUID 2:'),
        ),
    ]
