# Generated by Django 4.2.2 on 2023-06-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0010_remove_licencekey_uuid1_remove_licencekey_uuid2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licencekey',
            name='disk_serial_number1',
            field=models.BigIntegerField(blank=True, help_text='Disk seri numarasi', null=True, verbose_name='DSN 1:'),
        ),
        migrations.AlterField(
            model_name='licencekey',
            name='disk_serial_number2',
            field=models.BigIntegerField(blank=True, help_text='Disk seri numarasi', null=True, verbose_name='DSN 2:'),
        ),
    ]
