# Generated by Django 4.2.2 on 2023-07-27 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0011_alter_licencekey_disk_serial_number1_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LicenceKey',
            new_name='LicenseKey',
        ),
    ]
