# Generated by Django 4.2.2 on 2023-08-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0012_rename_licencekey_licensekey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensekey',
            name='key_type',
            field=models.CharField(choices=[('STD', 'Standart'), ('PRO', 'Profesyonel')], default='STD', verbose_name='Lisans tipi:'),
        ),
    ]
