# Generated by Django 4.2.2 on 2023-06-12 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Duyuru kapak fotoğrafı.')),
                ('title', models.CharField(verbose_name='Duyuru başlığı.')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Duyuru tarihi.')),
                ('text', models.CharField(verbose_name='Duyuru içeriği')),
            ],
        ),
    ]
