# Generated by Django 5.1.4 on 2024-12-19 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='images/announcements/thumbnails/%Y/%m/%d', verbose_name='Duyuru kapak fotoğrafı.')),
                ('title', models.CharField(max_length=64, verbose_name='Duyuru başlığı.')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Duyuru tarihi.')),
                ('content', models.CharField(max_length=4096, verbose_name='Duyuru içeriği')),
            ],
        ),
    ]
