# Generated by Django 4.2.2 on 2023-06-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Duyuru kapak fotoğrafı.'),
        ),
    ]
