# Generated by Django 4.2.2 on 2023-06-12 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_alter_announcement_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='text',
            new_name='content',
        ),
    ]
