# Generated by Django 4.2.2 on 2023-06-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_rename_text_announcement_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='image',
            field=models.ImageField(null=True, upload_to='media/images/announcements/thumbnails/%Y/%m/%d', verbose_name='Duyuru kapak fotoğrafı.'),
        ),
    ]
