# Generated by Django 4.2.2 on 2023-06-29 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0004_alter_announcement_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='image',
            field=models.ImageField(null=True, upload_to='images/announcements/thumbnails/%Y/%m/%d', verbose_name='Duyuru kapak fotoğrafı.'),
        ),
    ]
