# Generated by Django 5.1.4 on 2024-12-19 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='images/features/thumbnails/%Y/%m/%d', verbose_name='Görsel')),
                ('title', models.CharField(max_length=32, verbose_name='Başlık')),
                ('side_title', models.CharField(max_length=32, verbose_name='Yan başlık')),
                ('content', models.CharField(max_length=1024, verbose_name='İçerik')),
                ('side', models.CharField(choices=[('LEFT', 'Sol'), ('RIGHT', 'Sağ')], default='LEFT', max_length=32, verbose_name='Metin yönü')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Eklenme tarihi.')),
            ],
        ),
        migrations.CreateModel(
            name='Heading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='images/headings/thumbnails/%Y/%m/%d', verbose_name='Görsel')),
                ('title', models.CharField(max_length=32, verbose_name='Başlık')),
                ('content', models.CharField(max_length=1024, verbose_name='İçerik')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Eklenme tarihi.')),
            ],
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='images/slide_thumbnails/%Y/%m/%d', verbose_name='Görsel')),
                ('title', models.CharField(max_length=32, verbose_name='Başlık')),
                ('content', models.CharField(max_length=1024, verbose_name='İçerik')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Eklenme tarihi.')),
            ],
        ),
    ]
