# Generated by Django 4.2.2 on 2023-06-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_heading_rename_text_feature_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='Görsel')),
                ('title', models.CharField(verbose_name='Başlık')),
                ('content', models.CharField(verbose_name='İçerik')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Eklenme tarihi.')),
            ],
        ),
    ]
