# Generated by Django 4.2.2 on 2023-06-12 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_slide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='image',
            field=models.ImageField(null=True, upload_to='media/images/features/%Y/%m/%d', verbose_name='Görsel'),
        ),
        migrations.AlterField(
            model_name='heading',
            name='image',
            field=models.ImageField(null=True, upload_to='media/images/headings/%Y/%m/%d', verbose_name='Görsel'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=models.ImageField(null=True, upload_to='media/images/slides/%Y/%m/%d', verbose_name='Görsel'),
        ),
    ]
