# Generated by Django 4.2.2 on 2023-06-29 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_feature_image_alter_feature_side_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='image',
            field=models.ImageField(null=True, upload_to='images/features/thumbnails/%Y/%m/%d', verbose_name='Görsel'),
        ),
        migrations.AlterField(
            model_name='heading',
            name='image',
            field=models.ImageField(null=True, upload_to='images/headings/thumbnails/%Y/%m/%d', verbose_name='Görsel'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=models.ImageField(null=True, upload_to='images/slide_thumbnails/%Y/%m/%d', verbose_name='Görsel'),
        ),
    ]
